# Generated by Django 4.2.16 on 2024-09-30 23:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profila',
            new_name='Profile',
        ),
    ]
